version: '3'

tasks:
  install:
    desc: Install dependencies
    dir: webapp
    cmds:
      - bun install

  build:
    desc: Build the plugin
    dir: webapp
    deps: [install]
    cmds:
      - bun run build

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf webapp/dist
      - rm -rf dist

  package:
    desc: Package the plugin
    deps: [build]
    cmds:
      - mkdir -p dist
      - tar -czf dist/mattermost-mentions-menu-plugin.tar.gz plugin.json webapp/dist/main.js

  dev:
    desc: Start development mode with watching
    dir: webapp
    cmds:
      - bun run dev

  default:
    desc: Clean, build and package the plugin
    cmds:
      - task: clean
      - task: package

  deploy:
    desc: Clean, build, package and deploy to local Mattermost server
    cmds:
      - task: default
      - echo "Upload dist/mattermost-mentions-menu-plugin.tar.gz to your Mattermost server"
      - echo "Access System Console > Plugins Management > Upload Plugin"
